apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: deo
  name: deo-frontend-dep-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deo-frontend
      version: prod
  template:
    metadata:
      labels:
        app: deo-frontend
        version: prod
    spec:
      imagePullSecrets:
        - name: ghcr-login-secret
      containers:
        - name: deo-frontend
          image: ghcr.io/skastenhofer/deo-webapp-frontend:v2.2
          args: ["--urls", "http://*:2000"]
          ports:
            - containerPort: 2000
          env:
            - name: DEO_BACKEND_URL
              value: "http://deo-backend-svc:3000"
---
apiVersion: v1
kind: Service
metadata:
  namespace: deo
  name: deo-frontend-svc-prod
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 2000
      targetPort: 2000
  selector:
    app: deo-frontend
    version: prod
