name: Release Pipeline

run-name: Release triggered by ${{ github.actor }} 👌

on:
    push:
        tags:
            - v*

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Set up .NET 8
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: 8
            - name: create release
              run: |
                gh release create
                